[2025-07-25T02:00:23.511+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-07-25T02:00:23.599+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: tunestream_etl_pipeline.Load_user_dim_table manual__2025-07-25T01:56:10.906355+00:00 [queued]>
[2025-07-25T02:00:23.622+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: tunestream_etl_pipeline.Load_user_dim_table manual__2025-07-25T01:56:10.906355+00:00 [queued]>
[2025-07-25T02:00:23.625+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-07-25T02:00:23.662+0000] {taskinstance.py:2330} INFO - Executing <Task(PostgresOperator): Load_user_dim_table> on 2025-07-25 01:56:10.906355+00:00
[2025-07-25T02:00:23.693+0000] {standard_task_runner.py:63} INFO - Started process 153 to run task
[2025-07-25T02:00:23.729+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'tunestream_etl_pipeline', 'Load_user_dim_table', 'manual__2025-07-25T01:56:10.906355+00:00', '--job-id', '58', '--raw', '--subdir', 'DAGS_FOLDER/final_exam_src.py', '--cfg-path', '/tmp/tmpcvh2ro69']
[2025-07-25T02:00:23.744+0000] {standard_task_runner.py:91} INFO - Job 58: Subtask Load_user_dim_table
[2025-07-25T02:00:24.037+0000] {task_command.py:426} INFO - Running <TaskInstance: tunestream_etl_pipeline.Load_user_dim_table manual__2025-07-25T01:56:10.906355+00:00 [running]> on host f09e52be76ce
[2025-07-25T02:00:24.362+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='QuangBLM1' AIRFLOW_CTX_DAG_ID='tunestream_etl_pipeline' AIRFLOW_CTX_TASK_ID='Load_user_dim_table' AIRFLOW_CTX_EXECUTION_DATE='2025-07-25T01:56:10.906355+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-25T01:56:10.906355+00:00'
[2025-07-25T02:00:24.367+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-07-25T02:00:24.369+0000] {sql.py:276} INFO - Executing: 
        TRUNCATE TABLE users;
        INSERT INTO users (userid, first_name, last_name, gender, "level")
        SELECT distinct userid, firstname, lastname, gender, "level"
        FROM staging_events
        WHERE page='NextSong';
    
[2025-07-25T02:00:24.395+0000] {base.py:84} INFO - Using connection ID 'postgres_default' for task execution.
[2025-07-25T02:00:24.426+0000] {base.py:84} INFO - Using connection ID 'postgres_default' for task execution.
[2025-07-25T02:00:24.441+0000] {sql.py:487} INFO - Running statement: 
        TRUNCATE TABLE users;
        INSERT INTO users (userid, first_name, last_name, gender, "level")
        SELECT distinct userid, firstname, lastname, gender, "level"
        FROM staging_events
        WHERE page='NextSong';
    , parameters: None
[2025-07-25T02:00:24.494+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-07-25T02:00:24.496+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/common/sql/operators/sql.py", line 282, in execute
    output = hook.run(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/common/sql/hooks/sql.py", line 435, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/common/sql/hooks/sql.py", line 492, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "users_pkey"
DETAIL:  Key (userid)=(88) already exists.

[2025-07-25T02:00:24.519+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=tunestream_etl_pipeline, task_id=Load_user_dim_table, run_id=manual__2025-07-25T01:56:10.906355+00:00, execution_date=20250725T015610, start_date=20250725T020023, end_date=20250725T020024
[2025-07-25T02:00:24.549+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 58 for task Load_user_dim_table (duplicate key value violates unique constraint "users_pkey"
DETAIL:  Key (userid)=(88) already exists.
; 153)
[2025-07-25T02:00:24.622+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-07-25T02:00:24.656+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.10/site-packages/***/models/baseoperator.py:1297: AirflowProviderDeprecationWarning: Call to deprecated class PostgresOperator. (Please use `***.providers.common.sql.operators.sql.SQLExecuteQueryOperator`.Also, you can provide `hook_params={'schema': <database>}`.)
  result = cls.__new__(cls)

[2025-07-25T02:00:24.696+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-07-25T02:00:24.704+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
