[2025-07-24T15:29:05.609+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-07-24T15:29:05.665+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: tunestream_etl_pipeline.Stage_events scheduled__2025-07-24T11:00:00+00:00 [queued]>
[2025-07-24T15:29:05.685+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: tunestream_etl_pipeline.Stage_events scheduled__2025-07-24T11:00:00+00:00 [queued]>
[2025-07-24T15:29:05.688+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 4
[2025-07-24T15:29:05.718+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): Stage_events> on 2025-07-24 11:00:00+00:00
[2025-07-24T15:29:05.735+0000] {standard_task_runner.py:63} INFO - Started process 348 to run task
[2025-07-24T15:29:05.743+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'tunestream_etl_pipeline', 'Stage_events', 'scheduled__2025-07-24T11:00:00+00:00', '--job-id', '64', '--raw', '--subdir', 'DAGS_FOLDER/final_exam_src.py', '--cfg-path', '/tmp/tmp2jqkodlt']
[2025-07-24T15:29:05.750+0000] {standard_task_runner.py:91} INFO - Job 64: Subtask Stage_events
[2025-07-24T15:29:05.876+0000] {task_command.py:426} INFO - Running <TaskInstance: tunestream_etl_pipeline.Stage_events scheduled__2025-07-24T11:00:00+00:00 [running]> on host 12caace40239
[2025-07-24T15:29:06.106+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='tunestream_etl_pipeline' AIRFLOW_CTX_TASK_ID='Stage_events' AIRFLOW_CTX_EXECUTION_DATE='2025-07-24T11:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-07-24T11:00:00+00:00'
[2025-07-24T15:29:06.112+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-07-24T15:29:06.153+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-07-24T15:29:06.177+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/final_exam_src.py", line 105, in load_logs_into_table
    postgres_hook.run(insert_sql, parameters=(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/common/sql/hooks/sql.py", line 431, in run
    with self._create_autocommit_connection(autocommit) as conn:
  File "/usr/local/lib/python3.10/contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/common/sql/hooks/sql.py", line 551, in _create_autocommit_connection
    with closing(self.get_conn()) as conn:
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/postgres/hooks/postgres.py", line 145, in get_conn
    conn = deepcopy(self.connection or self.get_connection(conn_id))
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/hooks/base.py", line 83, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/connection.py", line 519, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `postgres_default` isn't defined
[2025-07-24T15:29:06.196+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=tunestream_etl_pipeline, task_id=Stage_events, run_id=scheduled__2025-07-24T11:00:00+00:00, execution_date=20250724T110000, start_date=20250724T152905, end_date=20250724T152906
[2025-07-24T15:29:06.224+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 64 for task Stage_events (The conn_id `postgres_default` isn't defined; 348)
[2025-07-24T15:29:06.280+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-07-24T15:29:06.306+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.10/site-packages/***/models/baseoperator.py:1297: AirflowProviderDeprecationWarning: Call to deprecated class PostgresOperator. (Please use `***.providers.common.sql.operators.sql.SQLExecuteQueryOperator`.Also, you can provide `hook_params={'schema': <database>}`.)
  result = cls.__new__(cls)

[2025-07-24T15:29:06.338+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-07-24T15:29:06.342+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2025-07-24T15:40:30.282+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-07-24T15:40:30.443+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: tunestream_etl_pipeline.Stage_events scheduled__2025-07-24T11:00:00+00:00 [queued]>
[2025-07-24T15:40:30.467+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: tunestream_etl_pipeline.Stage_events scheduled__2025-07-24T11:00:00+00:00 [queued]>
[2025-07-24T15:40:30.468+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 4
[2025-07-24T15:40:30.503+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): Stage_events> on 2025-07-24 11:00:00+00:00
[2025-07-24T15:40:30.543+0000] {standard_task_runner.py:63} INFO - Started process 330 to run task
[2025-07-24T15:40:30.571+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'tunestream_etl_pipeline', 'Stage_events', 'scheduled__2025-07-24T11:00:00+00:00', '--job-id', '58', '--raw', '--subdir', 'DAGS_FOLDER/final_exam_src.py', '--cfg-path', '/tmp/tmpttsxhxae']
[2025-07-24T15:40:30.589+0000] {standard_task_runner.py:91} INFO - Job 58: Subtask Stage_events
[2025-07-24T15:40:30.823+0000] {task_command.py:426} INFO - Running <TaskInstance: tunestream_etl_pipeline.Stage_events scheduled__2025-07-24T11:00:00+00:00 [running]> on host 562a5fa0e436
[2025-07-24T15:40:31.011+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='QuangBLM1' AIRFLOW_CTX_DAG_ID='tunestream_etl_pipeline' AIRFLOW_CTX_TASK_ID='Stage_events' AIRFLOW_CTX_EXECUTION_DATE='2025-07-24T11:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-07-24T11:00:00+00:00'
[2025-07-24T15:40:31.017+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-07-24T15:40:31.056+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-07-24T15:40:31.077+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/final_exam_src.py", line 105, in load_logs_into_table
    postgres_hook.run(insert_sql, parameters=(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/common/sql/hooks/sql.py", line 431, in run
    with self._create_autocommit_connection(autocommit) as conn:
  File "/usr/local/lib/python3.10/contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/common/sql/hooks/sql.py", line 551, in _create_autocommit_connection
    with closing(self.get_conn()) as conn:
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/postgres/hooks/postgres.py", line 145, in get_conn
    conn = deepcopy(self.connection or self.get_connection(conn_id))
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/hooks/base.py", line 83, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/connection.py", line 519, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `postgres_default` isn't defined
[2025-07-24T15:40:31.099+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=tunestream_etl_pipeline, task_id=Stage_events, run_id=scheduled__2025-07-24T11:00:00+00:00, execution_date=20250724T110000, start_date=20250724T154030, end_date=20250724T154031
[2025-07-24T15:40:31.130+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 58 for task Stage_events (The conn_id `postgres_default` isn't defined; 330)
[2025-07-24T15:40:31.200+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-07-24T15:40:31.224+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.10/site-packages/***/models/baseoperator.py:1297: AirflowProviderDeprecationWarning: Call to deprecated class PostgresOperator. (Please use `***.providers.common.sql.operators.sql.SQLExecuteQueryOperator`.Also, you can provide `hook_params={'schema': <database>}`.)
  result = cls.__new__(cls)

[2025-07-24T15:40:31.260+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-07-24T15:40:31.266+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
