[2025-07-24T16:03:57.295+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-07-24T16:03:57.328+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: tunestream_etl_pipeline.Stage_songs manual__2025-07-24T16:03:53.447551+00:00 [queued]>
[2025-07-24T16:03:57.344+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: tunestream_etl_pipeline.Stage_songs manual__2025-07-24T16:03:53.447551+00:00 [queued]>
[2025-07-24T16:03:57.345+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 4
[2025-07-24T16:03:57.360+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): Stage_songs> on 2025-07-24 16:03:53.447551+00:00
[2025-07-24T16:03:57.372+0000] {standard_task_runner.py:63} INFO - Started process 868 to run task
[2025-07-24T16:03:57.378+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'tunestream_etl_pipeline', 'Stage_songs', 'manual__2025-07-24T16:03:53.447551+00:00', '--job-id', '144', '--raw', '--subdir', 'DAGS_FOLDER/final_exam_src.py', '--cfg-path', '/tmp/tmp38ub48_5']
[2025-07-24T16:03:57.383+0000] {standard_task_runner.py:91} INFO - Job 144: Subtask Stage_songs
[2025-07-24T16:03:57.480+0000] {task_command.py:426} INFO - Running <TaskInstance: tunestream_etl_pipeline.Stage_songs manual__2025-07-24T16:03:53.447551+00:00 [running]> on host 562a5fa0e436
[2025-07-24T16:03:57.600+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='QuangBLM1' AIRFLOW_CTX_DAG_ID='tunestream_etl_pipeline' AIRFLOW_CTX_TASK_ID='Stage_songs' AIRFLOW_CTX_EXECUTION_DATE='2025-07-24T16:03:53.447551+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-24T16:03:53.447551+00:00'
[2025-07-24T16:03:57.603+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-07-24T16:03:57.656+0000] {base.py:84} INFO - Using connection ID 'postgres_default' for task execution.
[2025-07-24T16:03:57.659+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-07-24T16:03:57.660+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/final_exam_src.py", line 79, in load_songs_into_table
    postgres_hook.run(insert_sql, parameters=(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/common/sql/hooks/sql.py", line 431, in run
    with self._create_autocommit_connection(autocommit) as conn:
  File "/usr/local/lib/python3.10/contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/common/sql/hooks/sql.py", line 551, in _create_autocommit_connection
    with closing(self.get_conn()) as conn:
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/postgres/hooks/postgres.py", line 175, in get_conn
    self.conn = psycopg2.connect(**conn_args)
  File "/home/airflow/.local/lib/python3.10/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "127.17.0.2", port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?

[2025-07-24T16:03:57.685+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=tunestream_etl_pipeline, task_id=Stage_songs, run_id=manual__2025-07-24T16:03:53.447551+00:00, execution_date=20250724T160353, start_date=20250724T160357, end_date=20250724T160357
[2025-07-24T16:03:57.702+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 144 for task Stage_songs (connection to server at "127.17.0.2", port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
; 868)
[2025-07-24T16:03:57.752+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-07-24T16:03:57.770+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.10/site-packages/***/models/baseoperator.py:1297: AirflowProviderDeprecationWarning: Call to deprecated class PostgresOperator. (Please use `***.providers.common.sql.operators.sql.SQLExecuteQueryOperator`.Also, you can provide `hook_params={'schema': <database>}`.)
  result = cls.__new__(cls)

[2025-07-24T16:03:57.792+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-07-24T16:03:57.797+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
