[2025-07-24T15:29:02.990+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-07-24T15:29:03.085+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: tunestream_etl_pipeline.Stage_songs scheduled__2025-07-24T10:00:00+00:00 [queued]>
[2025-07-24T15:29:03.130+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: tunestream_etl_pipeline.Stage_songs scheduled__2025-07-24T10:00:00+00:00 [queued]>
[2025-07-24T15:29:03.139+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 4
[2025-07-24T15:29:03.219+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): Stage_songs> on 2025-07-24 10:00:00+00:00
[2025-07-24T15:29:03.262+0000] {standard_task_runner.py:63} INFO - Started process 339 to run task
[2025-07-24T15:29:03.271+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'tunestream_etl_pipeline', 'Stage_songs', 'scheduled__2025-07-24T10:00:00+00:00', '--job-id', '57', '--raw', '--subdir', 'DAGS_FOLDER/final_exam_src.py', '--cfg-path', '/tmp/tmpmjv5vhlj']
[2025-07-24T15:29:03.278+0000] {standard_task_runner.py:91} INFO - Job 57: Subtask Stage_songs
[2025-07-24T15:29:03.585+0000] {task_command.py:426} INFO - Running <TaskInstance: tunestream_etl_pipeline.Stage_songs scheduled__2025-07-24T10:00:00+00:00 [running]> on host 12caace40239
[2025-07-24T15:29:03.978+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='tunestream_etl_pipeline' AIRFLOW_CTX_TASK_ID='Stage_songs' AIRFLOW_CTX_EXECUTION_DATE='2025-07-24T10:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-07-24T10:00:00+00:00'
[2025-07-24T15:29:03.994+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-07-24T15:29:04.098+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-07-24T15:29:04.143+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/final_exam_src.py", line 79, in load_songs_into_table
    postgres_hook.run(insert_sql, parameters=(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/common/sql/hooks/sql.py", line 431, in run
    with self._create_autocommit_connection(autocommit) as conn:
  File "/usr/local/lib/python3.10/contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/common/sql/hooks/sql.py", line 551, in _create_autocommit_connection
    with closing(self.get_conn()) as conn:
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/postgres/hooks/postgres.py", line 145, in get_conn
    conn = deepcopy(self.connection or self.get_connection(conn_id))
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/hooks/base.py", line 83, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/connection.py", line 519, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `postgres_default` isn't defined
[2025-07-24T15:29:04.169+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=tunestream_etl_pipeline, task_id=Stage_songs, run_id=scheduled__2025-07-24T10:00:00+00:00, execution_date=20250724T100000, start_date=20250724T152903, end_date=20250724T152904
[2025-07-24T15:29:04.215+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 57 for task Stage_songs (The conn_id `postgres_default` isn't defined; 339)
[2025-07-24T15:29:04.300+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-07-24T15:29:04.332+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.10/site-packages/***/models/baseoperator.py:1297: AirflowProviderDeprecationWarning: Call to deprecated class PostgresOperator. (Please use `***.providers.common.sql.operators.sql.SQLExecuteQueryOperator`.Also, you can provide `hook_params={'schema': <database>}`.)
  result = cls.__new__(cls)

[2025-07-24T15:29:04.386+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-07-24T15:29:04.397+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2025-07-24T15:40:27.844+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-07-24T15:40:27.969+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: tunestream_etl_pipeline.Stage_songs scheduled__2025-07-24T10:00:00+00:00 [queued]>
[2025-07-24T15:40:28.005+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: tunestream_etl_pipeline.Stage_songs scheduled__2025-07-24T10:00:00+00:00 [queued]>
[2025-07-24T15:40:28.007+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 4
[2025-07-24T15:40:28.574+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): Stage_songs> on 2025-07-24 10:00:00+00:00
[2025-07-24T15:40:28.597+0000] {standard_task_runner.py:63} INFO - Started process 319 to run task
[2025-07-24T15:40:28.610+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'tunestream_etl_pipeline', 'Stage_songs', 'scheduled__2025-07-24T10:00:00+00:00', '--job-id', '54', '--raw', '--subdir', 'DAGS_FOLDER/final_exam_src.py', '--cfg-path', '/tmp/tmpgdeklv5u']
[2025-07-24T15:40:28.629+0000] {standard_task_runner.py:91} INFO - Job 54: Subtask Stage_songs
[2025-07-24T15:40:28.885+0000] {task_command.py:426} INFO - Running <TaskInstance: tunestream_etl_pipeline.Stage_songs scheduled__2025-07-24T10:00:00+00:00 [running]> on host 562a5fa0e436
[2025-07-24T15:40:29.292+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='QuangBLM1' AIRFLOW_CTX_DAG_ID='tunestream_etl_pipeline' AIRFLOW_CTX_TASK_ID='Stage_songs' AIRFLOW_CTX_EXECUTION_DATE='2025-07-24T10:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-07-24T10:00:00+00:00'
[2025-07-24T15:40:29.300+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-07-24T15:40:29.450+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-07-24T15:40:29.496+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/final_exam_src.py", line 79, in load_songs_into_table
    postgres_hook.run(insert_sql, parameters=(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/common/sql/hooks/sql.py", line 431, in run
    with self._create_autocommit_connection(autocommit) as conn:
  File "/usr/local/lib/python3.10/contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/common/sql/hooks/sql.py", line 551, in _create_autocommit_connection
    with closing(self.get_conn()) as conn:
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/postgres/hooks/postgres.py", line 145, in get_conn
    conn = deepcopy(self.connection or self.get_connection(conn_id))
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/hooks/base.py", line 83, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/connection.py", line 519, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `postgres_default` isn't defined
[2025-07-24T15:40:29.551+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=tunestream_etl_pipeline, task_id=Stage_songs, run_id=scheduled__2025-07-24T10:00:00+00:00, execution_date=20250724T100000, start_date=20250724T154027, end_date=20250724T154029
[2025-07-24T15:40:29.594+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 54 for task Stage_songs (The conn_id `postgres_default` isn't defined; 319)
[2025-07-24T15:40:29.686+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-07-24T15:40:29.719+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
