[2025-07-25T02:09:53.187+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-07-25T02:09:53.218+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: tunestream_etl_pipeline.Load_time_dim_table manual__2025-07-25T02:05:18.442262+00:00 [queued]>
[2025-07-25T02:09:53.228+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: tunestream_etl_pipeline.Load_time_dim_table manual__2025-07-25T02:05:18.442262+00:00 [queued]>
[2025-07-25T02:09:53.229+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2025-07-25T02:09:53.246+0000] {taskinstance.py:2330} INFO - Executing <Task(PostgresOperator): Load_time_dim_table> on 2025-07-25 02:05:18.442262+00:00
[2025-07-25T02:09:53.257+0000] {standard_task_runner.py:63} INFO - Started process 301 to run task
[2025-07-25T02:09:53.262+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'tunestream_etl_pipeline', 'Load_time_dim_table', 'manual__2025-07-25T02:05:18.442262+00:00', '--job-id', '70', '--raw', '--subdir', 'DAGS_FOLDER/final_exam_src.py', '--cfg-path', '/tmp/tmph4s_8x1e']
[2025-07-25T02:09:53.266+0000] {standard_task_runner.py:91} INFO - Job 70: Subtask Load_time_dim_table
[2025-07-25T02:09:53.346+0000] {task_command.py:426} INFO - Running <TaskInstance: tunestream_etl_pipeline.Load_time_dim_table manual__2025-07-25T02:05:18.442262+00:00 [running]> on host f09e52be76ce
[2025-07-25T02:09:53.446+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='QuangBLM1' AIRFLOW_CTX_DAG_ID='tunestream_etl_pipeline' AIRFLOW_CTX_TASK_ID='Load_time_dim_table' AIRFLOW_CTX_EXECUTION_DATE='2025-07-25T02:05:18.442262+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-25T02:05:18.442262+00:00'
[2025-07-25T02:09:53.449+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-07-25T02:09:53.449+0000] {sql.py:276} INFO - Executing: 
        TRUNCATE TABLE "time";
        INSERT INTO "time" (start_time, "hour", "day", week, "month", "year", weekday)
        SELECT 
            start_time, 
            extract(hour from start_time), 
            extract(day from start_time), 
            extract(week from start_time), 
            extract(month from start_time), 
            extract(year from start_time), 
            extract(dow from start_time) -- CORRECTED: Changed dayofweek to dow
        FROM songplays;
    
[2025-07-25T02:09:53.462+0000] {base.py:84} INFO - Using connection ID 'postgres_default' for task execution.
[2025-07-25T02:09:53.477+0000] {base.py:84} INFO - Using connection ID 'postgres_default' for task execution.
[2025-07-25T02:09:53.487+0000] {sql.py:487} INFO - Running statement: 
        TRUNCATE TABLE "time";
        INSERT INTO "time" (start_time, "hour", "day", week, "month", "year", weekday)
        SELECT 
            start_time, 
            extract(hour from start_time), 
            extract(day from start_time), 
            extract(week from start_time), 
            extract(month from start_time), 
            extract(year from start_time), 
            extract(dow from start_time) -- CORRECTED: Changed dayofweek to dow
        FROM songplays;
    , parameters: None
[2025-07-25T02:09:53.516+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-07-25T02:09:53.517+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/common/sql/operators/sql.py", line 282, in execute
    output = hook.run(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/common/sql/hooks/sql.py", line 435, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/common/sql/hooks/sql.py", line 492, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "time_pkey"
DETAIL:  Key (start_time)=(2018-11-14 04:53:36) already exists.

[2025-07-25T02:09:53.528+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=tunestream_etl_pipeline, task_id=Load_time_dim_table, run_id=manual__2025-07-25T02:05:18.442262+00:00, execution_date=20250725T020518, start_date=20250725T020953, end_date=20250725T020953
[2025-07-25T02:09:53.545+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 70 for task Load_time_dim_table (duplicate key value violates unique constraint "time_pkey"
DETAIL:  Key (start_time)=(2018-11-14 04:53:36) already exists.
; 301)
[2025-07-25T02:09:53.596+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-07-25T02:09:53.611+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.10/site-packages/***/models/baseoperator.py:1297: AirflowProviderDeprecationWarning: Call to deprecated class PostgresOperator. (Please use `***.providers.common.sql.operators.sql.SQLExecuteQueryOperator`.Also, you can provide `hook_params={'schema': <database>}`.)
  result = cls.__new__(cls)

[2025-07-25T02:09:53.627+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-07-25T02:09:53.636+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
